<Project>
  <PropertyGroup>
    <ZletProductName>Zlet Converter</ZletProductName>
    <ZletProductVersion>0.1.0</ZletProductVersion>
    <ZletExecutableName>ZletConverter</ZletExecutableName>
    <ZletPortableRuntimeIdentifier>win-x64</ZletPortableRuntimeIdentifier>
    <Version>$(ZletProductVersion)</Version>
    <AssemblyVersion>$(ZletProductVersion).0</AssemblyVersion>
    <FileVersion>$(ZletProductVersion).0</FileVersion>
    <InformationalVersion>$(ZletProductVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Product>$(ZletProductName)</Product>
    <ZletDisplayVersion>v$(ZletProductVersion)</ZletDisplayVersion>
    <ZletPortablePackageName>$(ZletExecutableName)-$(ZletDisplayVersion)-$(ZletPortableRuntimeIdentifier)</ZletPortablePackageName>
  </PropertyGroup>
</Project>
