<Project>
  <PropertyGroup>
    <ZletProductName>Zlet Converter</ZletProductName>
    <ZletProductVersion>0.2.0-alpha</ZletProductVersion>
    <ZletAssemblyVersion>0.2.0.0</ZletAssemblyVersion>
    <ZletExecutableName>ZletConverter</ZletExecutableName>
    <ZletPortableRuntimeIdentifier>win-x64</ZletPortableRuntimeIdentifier>
    <Version>$(ZletProductVersion)</Version>
    <AssemblyVersion>$(ZletAssemblyVersion)</AssemblyVersion>
    <FileVersion>$(ZletAssemblyVersion)</FileVersion>
    <InformationalVersion>$(ZletProductVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Product>$(ZletProductName)</Product>
    <ZletDisplayVersion>v$(ZletProductVersion)</ZletDisplayVersion>
    <ZletPortablePackageName>$(ZletExecutableName)-$(ZletDisplayVersion)-$(ZletPortableRuntimeIdentifier)</ZletPortablePackageName>
  </PropertyGroup>
</Project>
