<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Zlet.FolderConverter.App\Zlet.FolderConverter.App.csproj" />
    <ProjectReference Include="..\..\src\Zlet.FolderConverter.Core\Zlet.FolderConverter.Core.csproj" />
    <ProjectReference Include="..\..\src\Zlet.FolderConverter.OfficeWorker\Zlet.FolderConverter.OfficeWorker.csproj" />
    <None Include="..\..\src\Zlet.FolderConverter.AnydocWorker\target\release\zlet-anydoc-worker.exe" Link="zlet-anydoc-worker.exe" CopyToOutputDirectory="PreserveNewest" Condition="Exists('..\..\src\Zlet.FolderConverter.AnydocWorker\target\release\zlet-anydoc-worker.exe')" />
  </ItemGroup>

</Project>
